cache:
  pip: true
  directories:
    - .stestr
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libblas-dev
      - liblapack-dev

install_osx: &stage_osx
  os: osx
  osx_image: xcode9.4
  language: generic
  cache:
    pip: true
    directories:
      - ~/python-interpreters/
      - .stestr
  before_install:
    # Travis does not provide support for Python 3 under osx - it needs to be
    # installed manually.
    |
    if [ ${TRAVIS_OS_NAME} = "osx" ]; then
      if [[ ! -d ~/python-interpreters/$PYTHON_VERSION ]]; then
        git clone git://github.com/pyenv/pyenv.git
        cd pyenv/plugins/python-build
        ./install.sh
        cd ../../..
        python-build $PYTHON_VERSION ~/python-interpreters/$PYTHON_VERSION
      fi
      sudo pip2 install -U virtualenv pip setuptools
      virtualenv --python ~/python-interpreters/$PYTHON_VERSION/bin/python venv
      source venv/bin/activate
    fi

stages:
 - lint_and_python
 - all_python

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35
      name: "Python 3.5 Tests"
      stage: all_python
    - python: "3.6"
      env: TOXENV=py36
      name: "Python 3.6 Tests"
      stage: all_python
    - os: linux
      dist: xenial
      python: "3.7"
      env: TOXENV=py37
      name: "Python 3.7 Tests"
      stage: lint_and_python
    - os: linux
      dist: xenial
      python: "3.8"
      env: TOXENV=py38
      name: "Python 3.8 Tests"
      stage: all_python
    - python: "3.7"
      dist: xenial
      env: TOXENV=lint
      name: "Linter Checks"
      stage: lint_and_python
    - stage: all_python
      name: "Python 3.5 Tests on OSX"
      <<: *stage_osx
      env:
        - MPLBACKEND=ps
        - PYTHON_VERSION=3.5.9
        - TOXENV=py35
    - stage: all_python
      name: "Python 3.6 Tests on OSX"
      <<: *stage_osx
      env:
        - MPLBACKEND=ps
        - PYTHON_VERSION=3.6.10
        - TOXENV=py36
    - stage: lint_and_python
      <<: *stage_osx
      name: "Python 3.7 Tests on OSX"
      env:
        - MPLBACKEND=ps
        - PYTHON_VERSION=3.7.6
        - TOXENV=py37
    - stage: all_python
      <<: *stage_osx
      name: "Python 3.8 Tests on OSX"
      if: type = cron
      env:
        - MPLBACKEND=ps
        - PYTHON_VERSION=3.8.1
        - TOXENV=py38
    - if: tag IS present
      python: "3.6"
      env:
        - TWINE_USERNAME=qiskit
      install: pip install -U twine
      script:
        - python3 setup.py sdist bdist_wheel
        - twine upload dist/qiskit*

language: python
install: pip install -U tox pip virtualenv setuptools six
script:
  - tox --notest
  - .tox/$TOXENV/bin/pip install --no-cache-dir cvxopt
  - tox

notifications:
  email: false
